apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  labels:
    app: ollama
spec:
  # TODO: this PVC needs to be writable by a single pod at a time, and
  # should request enough storage for a small model (~10GB should be enough).
