apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  # TODO: we only need to reach this from inside the cluster (the webui pod,
  # and your own machine via port-forward)
  # WE DO NOT need to expose it externally, just for this hw
